app_config:
  shared: &shared
    email_name: m2mRails WebBot
    email_address: m2mRails@example.com
    sales_email_name: m2mRails Sales
    sales_email_address: sales@example.com
    email_domain: example.com
    website: www.example.com
    short_name: m2mRails
    long_name: m2mRails Quickstart Site
    logo_image: logo.gif
    quote_logo_image: quote_logo.jpg
    use_boms: false
    production_hostname: m2mhub.example.com
    epoch_year: 2010
    use_item_revisions: true
  development:
    <<: *shared
    hostname: staging_m2mrails.example.com
  production:
    <<: *shared
    hostname: m2mrails.example.com
  test:
    <<: *shared
