development:
  encoding: utf8
  adapter: mysql
  database: m2mRails_dev
  pool: 5
  timeout: 5000
  username: xxxx
  password: xxxxxxxx

development_m2m:
  adapter: sqlserver
  mode: dblib
  host: dev_sqlserver_hostname_or_ip_address
  tds_version: 70
  database: xxxxxxx
  username: xxx
  password: xxxxxxx
  timeout: 5000
  encoding: utf8

production:
  encoding: utf8
  adapter: mysql
  database: m2mRails_prod
  pool: 5
  timeout: 5000
  username: root

production_m2m:
  adapter: sqlserver
  mode: dblib
  host: prod_sqlserver_hostname_or_ip_address
  tds_version: 70
  database: xxxxxxx
  username: xxx
  password: xxxxxxx
  timeout: 5000
  encoding: utf8
